### ISSUE TITLE
Review 1

### ISSUE THREAD

**Issue by vfaddey** [Sat1l/laba3#1]
### Naming Conventions
Названия всех enum и интерфейсов должны именоваться по тем же правилам, что и классы. Здесь же все названия enums капсом и есть интерфейсы, начинающиеся с маленькой буквы (hasOccasion, hasAlcohol)

(Мнение) Один из классов назван с использованием транслита, выглядит странно
https://github.com/Sat1l/laba3/blob/707543839443c2320cbfbfd9c8decefd8a41d38c/src/actions/NewTuchi.java#L7

### Ненужные методы 
Для чего нужен метод getLocname(), если ниже переопределен метод toString(), который позволяет убрать из кода лишние вызовы методов.
https://github.com/Sat1l/laba3/blob/707543839443c2320cbfbfd9c8decefd8a41d38c/src/parentclasses/Location.java#L17-L19

https://github.com/Sat1l/laba3/blob/707543839443c2320cbfbfd9c8decefd8a41d38c/src/parentclasses/Location.java#L30-L33

#### Работа метода bringTogether()
(Мнение)Странно, что проверяется, что только мужчина может приносить какие-либо предметы
https://github.com/Sat1l/laba3/blob/707543839443c2320cbfbfd9c8decefd8a41d38c/src/actions/BringTogether.java#L17-L18

#### Метод drinkAlco()
Было бы хорошо добавить проверку соответствия локации человека локации того, что он будет пить
https://github.com/Sat1l/laba3/blob/707543839443c2320cbfbfd9c8decefd8a41d38c/src/actions/DrinkAlco.java#L16

**Comment by vfaddey** [comment]
### Дополнение 
При создании объекта класса UObject устанавливается его локация, но в объекте локации не происходит изменений в поле uobjects. Метод setLocation также не добавляет этот предмет в список предметов самой локации. Из-за этого могут быть баги
https://github.com/Sat1l/laba3/blob/707543839443c2320cbfbfd9c8decefd8a41d38c/src/parentclasses/UObject.java#L9-L12
https://github.com/Sat1l/laba3/blob/707543839443c2320cbfbfd9c8decefd8a41d38c/src/parentclasses/UObject.java#L22-L24

Можно просто добавить `this.location.addItem(this)`.  И не забыть убрать предмет из старой локации, если требуется
В классах-наследниках та же проблема

**Comment by Sat1l** [comment]
@vfaddey В комите линкнутом выше пофиксил все проблемы, просьба прочекать

**Comment by vfaddey** [comment]
Все хорошо, можно закрывать
